(cf_if_tag "<cf" @open "</cf" @close)
(cf_function_tag "<cf" @open "</cf" @close)
(cf_output_tag "<cf" @open "</cf" @close)
(cf_script_tag "<cf" @open "</cf" @close)
(cf_query_tag "<cf" @open "</cf" @close)
(cf_savecontent_tag "<cf" @open "</cf" @close)
(cf_tag (cf_start_tag "<cf" @open) (cf_end_tag "</cf" @close))
(element (start_tag "<" @open) (end_tag "</" @close))
("{" @open "}" @close)
("[" @open "]" @close)
("(" @open ")" @close)
