#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 128
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  sym_cf_condition = 1,
  sym_cf_tag_start = 2,
  sym_cf_tag_end = 3,
  sym_text = 4,
  sym_cf_tag_close = 5,
  anon_sym_GT = 6,
  anon_sym_RBRACE = 7,
  anon_sym_SQUOTE = 8,
  aux_sym_quoted_attribute_value_token1 = 9,
  anon_sym_DQUOTE = 10,
  aux_sym_quoted_attribute_value_token2 = 11,
  anon_sym_EQ = 12,
  sym_attribute_name = 13,
  sym_attribute_value = 14,
  sym_cf_if_keyword = 15,
  sym_cf_elseif_keyword = 16,
  sym_cf_else_keyword = 17,
  sym_cf_function_keyword = 18,
  sym_fragment = 19,
  sym__node = 20,
  sym_cf_function = 21,
  sym_cf_ifstatement = 22,
  sym_cf_if = 23,
  sym_cf_elseif = 24,
  sym_cf_else = 25,
  sym_cf_if_end = 26,
  sym_quoted_attribute_value = 27,
  sym_attribute = 28,
  sym_cf_statement = 29,
  aux_sym_fragment_repeat1 = 30,
  aux_sym_cf_function_repeat1 = 31,
  aux_sym_cf_ifstatement_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_cf_condition] = "cf_condition",
  [sym_cf_tag_start] = "cf_tag_start",
  [sym_cf_tag_end] = "cf_tag_end",
  [sym_text] = "text",
  [sym_cf_tag_close] = "cf_tag_close",
  [anon_sym_GT] = ">",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_cf_if_keyword] = "cf_if_keyword",
  [sym_cf_elseif_keyword] = "cf_elseif_keyword",
  [sym_cf_else_keyword] = "cf_else_keyword",
  [sym_cf_function_keyword] = "cf_function_keyword",
  [sym_fragment] = "fragment",
  [sym__node] = "_node",
  [sym_cf_function] = "cf_function",
  [sym_cf_ifstatement] = "cf_ifstatement",
  [sym_cf_if] = "cf_if",
  [sym_cf_elseif] = "cf_elseif",
  [sym_cf_else] = "cf_else",
  [sym_cf_if_end] = "cf_if_end",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_attribute] = "attribute",
  [sym_cf_statement] = "cf_statement",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_cf_function_repeat1] = "cf_function_repeat1",
  [aux_sym_cf_ifstatement_repeat1] = "cf_ifstatement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_cf_condition] = sym_cf_condition,
  [sym_cf_tag_start] = sym_cf_tag_start,
  [sym_cf_tag_end] = sym_cf_tag_end,
  [sym_text] = sym_text,
  [sym_cf_tag_close] = sym_cf_tag_close,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_cf_if_keyword] = sym_cf_if_keyword,
  [sym_cf_elseif_keyword] = sym_cf_elseif_keyword,
  [sym_cf_else_keyword] = sym_cf_else_keyword,
  [sym_cf_function_keyword] = sym_cf_function_keyword,
  [sym_fragment] = sym_fragment,
  [sym__node] = sym__node,
  [sym_cf_function] = sym_cf_function,
  [sym_cf_ifstatement] = sym_cf_ifstatement,
  [sym_cf_if] = sym_cf_if,
  [sym_cf_elseif] = sym_cf_elseif,
  [sym_cf_else] = sym_cf_else,
  [sym_cf_if_end] = sym_cf_if_end,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_attribute] = sym_attribute,
  [sym_cf_statement] = sym_cf_statement,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_cf_function_repeat1] = aux_sym_cf_function_repeat1,
  [aux_sym_cf_ifstatement_repeat1] = aux_sym_cf_ifstatement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_cf_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_tag_start] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_tag_end] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_tag_close] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_if_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_elseif_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_else_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_function_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_cf_function] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_ifstatement] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_if] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_elseif] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_else] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_if_end] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_cf_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cf_function_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cf_ifstatement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 9,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 9,
  [25] = 25,
  [26] = 26,
  [27] = 23,
  [28] = 25,
  [29] = 25,
  [30] = 23,
  [31] = 26,
  [32] = 32,
  [33] = 22,
  [34] = 22,
  [35] = 26,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 38,
  [40] = 36,
  [41] = 38,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 47,
  [54] = 54,
  [55] = 45,
  [56] = 46,
  [57] = 43,
  [58] = 48,
  [59] = 44,
  [60] = 54,
  [61] = 49,
  [62] = 50,
  [63] = 51,
  [64] = 54,
  [65] = 42,
  [66] = 48,
  [67] = 43,
  [68] = 47,
  [69] = 50,
  [70] = 42,
  [71] = 49,
  [72] = 46,
  [73] = 45,
  [74] = 44,
  [75] = 51,
  [76] = 76,
  [77] = 76,
  [78] = 78,
  [79] = 78,
  [80] = 80,
  [81] = 81,
  [82] = 76,
  [83] = 78,
  [84] = 84,
  [85] = 85,
  [86] = 85,
  [87] = 87,
  [88] = 84,
  [89] = 84,
  [90] = 85,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 98,
  [105] = 99,
  [106] = 100,
  [107] = 101,
  [108] = 103,
  [109] = 109,
  [110] = 97,
  [111] = 111,
  [112] = 103,
  [113] = 109,
  [114] = 97,
  [115] = 111,
  [116] = 116,
  [117] = 109,
  [118] = 118,
  [119] = 98,
  [120] = 99,
  [121] = 121,
  [122] = 101,
  [123] = 123,
  [124] = 111,
  [125] = 125,
  [126] = 126,
  [127] = 100,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\'') ADVANCE(42);
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == '=') ADVANCE(48);
      if (lookahead == '>') ADVANCE(40);
      if (lookahead == 'e') ADVANCE(37);
      if (lookahead == 'f') ADVANCE(38);
      if (lookahead == 'i') ADVANCE(36);
      if (lookahead == '}') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '{') ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\'') ADVANCE(42);
      if (lookahead == '=') ADVANCE(48);
      if (lookahead == '>') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          lookahead != '/' &&
          lookahead != '<') ADVANCE(49);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\'') ADVANCE(42);
      if (lookahead == '>') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '=') ADVANCE(50);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == '>') ADVANCE(34);
      if (lookahead == 'e') ADVANCE(37);
      if (lookahead == 'f') ADVANCE(38);
      if (lookahead == 'i') ADVANCE(36);
      if (lookahead == '}') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '{') ADVANCE(35);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(51);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(39);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(52);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 28:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(32);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == '>') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(38);
      if (lookahead == 'i') ADVANCE(36);
      if (lookahead == '}') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(29)
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '{') ADVANCE(35);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_cf_condition);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_cf_condition);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_cf_tag_start);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_cf_tag_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'f') ADVANCE(51);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_cf_tag_close);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_cf_if_keyword);
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_cf_elseif_keyword);
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_cf_else_keyword);
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_cf_else_keyword);
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_cf_function_keyword);
      if (lookahead == 'f') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 29},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 29},
  [15] = {.lex_state = 29},
  [16] = {.lex_state = 29},
  [17] = {.lex_state = 29},
  [18] = {.lex_state = 29},
  [19] = {.lex_state = 29},
  [20] = {.lex_state = 29},
  [21] = {.lex_state = 29},
  [22] = {.lex_state = 29},
  [23] = {.lex_state = 29},
  [24] = {.lex_state = 29},
  [25] = {.lex_state = 29},
  [26] = {.lex_state = 29},
  [27] = {.lex_state = 29},
  [28] = {.lex_state = 29},
  [29] = {.lex_state = 29},
  [30] = {.lex_state = 29},
  [31] = {.lex_state = 29},
  [32] = {.lex_state = 29},
  [33] = {.lex_state = 29},
  [34] = {.lex_state = 29},
  [35] = {.lex_state = 29},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 6},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 6},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 29},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 29},
  [56] = {.lex_state = 29},
  [57] = {.lex_state = 29},
  [58] = {.lex_state = 29},
  [59] = {.lex_state = 29},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 29},
  [62] = {.lex_state = 29},
  [63] = {.lex_state = 29},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 29},
  [66] = {.lex_state = 29},
  [67] = {.lex_state = 29},
  [68] = {.lex_state = 29},
  [69] = {.lex_state = 29},
  [70] = {.lex_state = 29},
  [71] = {.lex_state = 29},
  [72] = {.lex_state = 29},
  [73] = {.lex_state = 29},
  [74] = {.lex_state = 29},
  [75] = {.lex_state = 29},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 29},
  [100] = {.lex_state = 29},
  [101] = {.lex_state = 29},
  [102] = {.lex_state = 28},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 29},
  [106] = {.lex_state = 29},
  [107] = {.lex_state = 29},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 28},
  [119] = {.lex_state = 2},
  [120] = {.lex_state = 29},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 29},
  [123] = {.lex_state = 28},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 1},
  [126] = {.lex_state = 1},
  [127] = {.lex_state = 29},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_cf_tag_start] = ACTIONS(1),
    [sym_cf_tag_end] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [sym_cf_tag_close] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_cf_if_keyword] = ACTIONS(1),
    [sym_cf_elseif_keyword] = ACTIONS(1),
    [sym_cf_else_keyword] = ACTIONS(1),
    [sym_cf_function_keyword] = ACTIONS(1),
  },
  [1] = {
    [sym_fragment] = STATE(121),
    [sym__node] = STATE(32),
    [sym_cf_function] = STATE(67),
    [sym_cf_ifstatement] = STATE(67),
    [sym_cf_if] = STATE(41),
    [sym_cf_statement] = STATE(32),
    [aux_sym_fragment_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_cf_tag_start] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
    [sym_cf_if_keyword] = ACTIONS(9),
    [sym_cf_function_keyword] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(13), 1,
      sym_cf_tag_start,
    ACTIONS(15), 1,
      sym_cf_tag_end,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(21), 1,
      sym_cf_else_keyword,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    ACTIONS(19), 3,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
    STATE(5), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [36] = 10,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(13), 1,
      sym_cf_tag_start,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    ACTIONS(25), 1,
      sym_cf_tag_end,
    ACTIONS(27), 1,
      sym_text,
    ACTIONS(31), 1,
      sym_cf_else_keyword,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    ACTIONS(29), 3,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
    STATE(12), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [72] = 10,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(13), 1,
      sym_cf_tag_start,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    ACTIONS(33), 1,
      sym_cf_tag_end,
    ACTIONS(35), 1,
      sym_text,
    ACTIONS(39), 1,
      sym_cf_else_keyword,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    ACTIONS(37), 3,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
    STATE(13), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [108] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    ACTIONS(43), 1,
      sym_text,
    ACTIONS(45), 1,
      sym_cf_else_keyword,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(9), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
    ACTIONS(41), 4,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
  [139] = 9,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(13), 1,
      sym_cf_tag_start,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    ACTIONS(47), 1,
      sym_text,
    ACTIONS(51), 1,
      sym_cf_else_keyword,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    ACTIONS(49), 3,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
    STATE(8), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [172] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    ACTIONS(43), 1,
      sym_text,
    ACTIONS(55), 1,
      sym_cf_else_keyword,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(9), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
    ACTIONS(53), 4,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
  [203] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    ACTIONS(43), 1,
      sym_text,
    ACTIONS(59), 1,
      sym_cf_else_keyword,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(9), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
    ACTIONS(57), 4,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
  [234] = 9,
    ACTIONS(61), 1,
      sym_cf_tag_start,
    ACTIONS(64), 1,
      sym_text,
    ACTIONS(69), 1,
      sym_cf_if_keyword,
    ACTIONS(72), 1,
      sym_cf_else_keyword,
    ACTIONS(74), 1,
      sym_cf_function_keyword,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    ACTIONS(67), 3,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
    STATE(9), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [267] = 9,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(13), 1,
      sym_cf_tag_start,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    ACTIONS(45), 1,
      sym_cf_else_keyword,
    ACTIONS(77), 1,
      sym_text,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    ACTIONS(41), 3,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
    STATE(7), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [300] = 9,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(13), 1,
      sym_cf_tag_start,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(21), 1,
      sym_cf_else_keyword,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    ACTIONS(19), 3,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
    STATE(5), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [333] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(21), 1,
      sym_cf_else_keyword,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    ACTIONS(43), 1,
      sym_text,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(9), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
    ACTIONS(19), 4,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
  [364] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    ACTIONS(43), 1,
      sym_text,
    ACTIONS(51), 1,
      sym_cf_else_keyword,
    STATE(38), 1,
      sym_cf_if,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(9), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
    ACTIONS(49), 4,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_elseif_keyword,
  [395] = 9,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(81), 1,
      sym_cf_tag_end,
    ACTIONS(83), 1,
      sym_text,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    STATE(39), 1,
      sym_cf_if,
    ACTIONS(85), 2,
      sym_cf_tag_close,
      anon_sym_RBRACE,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(18), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [427] = 9,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(89), 1,
      sym_cf_tag_end,
    ACTIONS(91), 1,
      sym_text,
    STATE(39), 1,
      sym_cf_if,
    ACTIONS(93), 2,
      sym_cf_tag_close,
      anon_sym_RBRACE,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(16), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [459] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(95), 1,
      sym_text,
    STATE(39), 1,
      sym_cf_if,
    ACTIONS(85), 2,
      sym_cf_tag_close,
      anon_sym_RBRACE,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(19), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [488] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(83), 1,
      sym_text,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    STATE(39), 1,
      sym_cf_if,
    ACTIONS(85), 2,
      sym_cf_tag_close,
      anon_sym_RBRACE,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(18), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [517] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(95), 1,
      sym_text,
    STATE(39), 1,
      sym_cf_if,
    ACTIONS(97), 2,
      sym_cf_tag_close,
      anon_sym_RBRACE,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(19), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [546] = 8,
    ACTIONS(69), 1,
      sym_cf_if_keyword,
    ACTIONS(99), 1,
      sym_cf_tag_start,
    ACTIONS(102), 1,
      sym_text,
    ACTIONS(105), 1,
      sym_cf_function_keyword,
    STATE(39), 1,
      sym_cf_if,
    ACTIONS(67), 2,
      sym_cf_tag_close,
      anon_sym_RBRACE,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(19), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [575] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(95), 1,
      sym_text,
    STATE(39), 1,
      sym_cf_if,
    ACTIONS(108), 2,
      sym_cf_tag_close,
      anon_sym_RBRACE,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(19), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [604] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(110), 1,
      sym_text,
    STATE(39), 1,
      sym_cf_if,
    ACTIONS(97), 2,
      sym_cf_tag_close,
      anon_sym_RBRACE,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(20), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [633] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(95), 1,
      sym_text,
    ACTIONS(112), 1,
      sym_cf_tag_close,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(19), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [661] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(114), 1,
      sym_text,
    ACTIONS(116), 1,
      sym_cf_tag_close,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(29), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [689] = 8,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      sym_cf_if_keyword,
    ACTIONS(118), 1,
      sym_cf_tag_start,
    ACTIONS(121), 1,
      sym_text,
    ACTIONS(124), 1,
      sym_cf_function_keyword,
    STATE(41), 1,
      sym_cf_if,
    STATE(67), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(24), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [717] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(95), 1,
      sym_text,
    ACTIONS(127), 1,
      sym_cf_tag_close,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(19), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [745] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(127), 1,
      sym_cf_tag_close,
    ACTIONS(129), 1,
      sym_text,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(34), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [773] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(131), 1,
      sym_text,
    ACTIONS(133), 1,
      sym_cf_tag_close,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(28), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [801] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(95), 1,
      sym_text,
    ACTIONS(135), 1,
      sym_cf_tag_close,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(19), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [829] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(95), 1,
      sym_text,
    ACTIONS(137), 1,
      sym_cf_tag_close,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(19), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [857] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(139), 1,
      sym_text,
    ACTIONS(141), 1,
      sym_cf_tag_close,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(25), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [885] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(135), 1,
      sym_cf_tag_close,
    ACTIONS(143), 1,
      sym_text,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(33), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [913] = 8,
    ACTIONS(5), 1,
      sym_cf_tag_start,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(11), 1,
      sym_cf_function_keyword,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(147), 1,
      sym_text,
    STATE(41), 1,
      sym_cf_if,
    STATE(67), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(24), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [941] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(95), 1,
      sym_text,
    ACTIONS(149), 1,
      sym_cf_tag_close,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(19), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [969] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(95), 1,
      sym_text,
    ACTIONS(151), 1,
      sym_cf_tag_close,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(19), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [997] = 8,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(79), 1,
      sym_cf_tag_start,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    ACTIONS(137), 1,
      sym_cf_tag_close,
    ACTIONS(153), 1,
      sym_text,
    STATE(39), 1,
      sym_cf_if,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
    STATE(22), 3,
      sym__node,
      sym_cf_statement,
      aux_sym_fragment_repeat1,
  [1025] = 8,
    ACTIONS(155), 1,
      sym_cf_tag_start,
    ACTIONS(157), 1,
      sym_cf_tag_close,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    ACTIONS(161), 1,
      sym_cf_elseif_keyword,
    ACTIONS(163), 1,
      sym_cf_else_keyword,
    STATE(66), 1,
      sym_cf_if_end,
    STATE(84), 1,
      sym_cf_else,
    STATE(52), 2,
      sym_cf_elseif,
      aux_sym_cf_ifstatement_repeat1,
  [1051] = 8,
    ACTIONS(155), 1,
      sym_cf_tag_start,
    ACTIONS(161), 1,
      sym_cf_elseif_keyword,
    ACTIONS(163), 1,
      sym_cf_else_keyword,
    ACTIONS(165), 1,
      sym_cf_tag_close,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_cf_if_end,
    STATE(88), 1,
      sym_cf_else,
    STATE(52), 2,
      sym_cf_elseif,
      aux_sym_cf_ifstatement_repeat1,
  [1077] = 8,
    ACTIONS(155), 1,
      sym_cf_tag_start,
    ACTIONS(161), 1,
      sym_cf_elseif_keyword,
    ACTIONS(163), 1,
      sym_cf_else_keyword,
    ACTIONS(169), 1,
      sym_cf_tag_close,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_cf_if_end,
    STATE(90), 1,
      sym_cf_else,
    STATE(40), 2,
      sym_cf_elseif,
      aux_sym_cf_ifstatement_repeat1,
  [1103] = 8,
    ACTIONS(155), 1,
      sym_cf_tag_start,
    ACTIONS(161), 1,
      sym_cf_elseif_keyword,
    ACTIONS(163), 1,
      sym_cf_else_keyword,
    ACTIONS(165), 1,
      sym_cf_tag_close,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      sym_cf_if_end,
    STATE(85), 1,
      sym_cf_else,
    STATE(37), 2,
      sym_cf_elseif,
      aux_sym_cf_ifstatement_repeat1,
  [1129] = 8,
    ACTIONS(155), 1,
      sym_cf_tag_start,
    ACTIONS(161), 1,
      sym_cf_elseif_keyword,
    ACTIONS(163), 1,
      sym_cf_else_keyword,
    ACTIONS(169), 1,
      sym_cf_tag_close,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      sym_cf_if_end,
    STATE(89), 1,
      sym_cf_else,
    STATE(52), 2,
      sym_cf_elseif,
      aux_sym_cf_ifstatement_repeat1,
  [1155] = 8,
    ACTIONS(155), 1,
      sym_cf_tag_start,
    ACTIONS(157), 1,
      sym_cf_tag_close,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    ACTIONS(161), 1,
      sym_cf_elseif_keyword,
    ACTIONS(163), 1,
      sym_cf_else_keyword,
    STATE(74), 1,
      sym_cf_if_end,
    STATE(86), 1,
      sym_cf_else,
    STATE(36), 2,
      sym_cf_elseif,
      aux_sym_cf_ifstatement_repeat1,
  [1181] = 2,
    ACTIONS(175), 2,
      sym_text,
      sym_cf_else_keyword,
    ACTIONS(173), 6,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_elseif_keyword,
      sym_cf_function_keyword,
  [1194] = 2,
    ACTIONS(179), 2,
      sym_text,
      sym_cf_else_keyword,
    ACTIONS(177), 6,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_elseif_keyword,
      sym_cf_function_keyword,
  [1207] = 2,
    ACTIONS(183), 2,
      sym_text,
      sym_cf_else_keyword,
    ACTIONS(181), 6,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_elseif_keyword,
      sym_cf_function_keyword,
  [1220] = 2,
    ACTIONS(187), 2,
      sym_text,
      sym_cf_else_keyword,
    ACTIONS(185), 6,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_elseif_keyword,
      sym_cf_function_keyword,
  [1233] = 2,
    ACTIONS(191), 2,
      sym_text,
      sym_cf_else_keyword,
    ACTIONS(189), 6,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_elseif_keyword,
      sym_cf_function_keyword,
  [1246] = 2,
    ACTIONS(195), 2,
      sym_text,
      sym_cf_else_keyword,
    ACTIONS(193), 6,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_elseif_keyword,
      sym_cf_function_keyword,
  [1259] = 2,
    ACTIONS(199), 2,
      sym_text,
      sym_cf_else_keyword,
    ACTIONS(197), 6,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_elseif_keyword,
      sym_cf_function_keyword,
  [1272] = 2,
    ACTIONS(203), 2,
      sym_text,
      sym_cf_else_keyword,
    ACTIONS(201), 6,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_elseif_keyword,
      sym_cf_function_keyword,
  [1285] = 2,
    ACTIONS(207), 2,
      sym_text,
      sym_cf_else_keyword,
    ACTIONS(205), 6,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_elseif_keyword,
      sym_cf_function_keyword,
  [1298] = 2,
    ACTIONS(211), 2,
      sym_text,
      sym_cf_else_keyword,
    ACTIONS(209), 6,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_elseif_keyword,
      sym_cf_function_keyword,
  [1311] = 5,
    ACTIONS(213), 1,
      sym_cf_tag_start,
    ACTIONS(218), 1,
      sym_cf_elseif_keyword,
    ACTIONS(221), 1,
      sym_cf_else_keyword,
    ACTIONS(216), 2,
      sym_cf_tag_close,
      anon_sym_RBRACE,
    STATE(52), 2,
      sym_cf_elseif,
      aux_sym_cf_ifstatement_repeat1,
  [1329] = 2,
    ACTIONS(195), 1,
      sym_text,
    ACTIONS(193), 5,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1340] = 5,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(11), 1,
      sym_cf_function_keyword,
    STATE(41), 1,
      sym_cf_if,
    STATE(72), 1,
      sym_cf_statement,
    STATE(67), 2,
      sym_cf_function,
      sym_cf_ifstatement,
  [1357] = 2,
    ACTIONS(187), 1,
      sym_text,
    ACTIONS(185), 5,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1368] = 2,
    ACTIONS(191), 1,
      sym_text,
    ACTIONS(189), 5,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1379] = 2,
    ACTIONS(179), 1,
      sym_text,
    ACTIONS(177), 5,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1390] = 2,
    ACTIONS(199), 1,
      sym_text,
    ACTIONS(197), 5,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1401] = 2,
    ACTIONS(183), 1,
      sym_text,
    ACTIONS(181), 5,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1412] = 5,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(87), 1,
      sym_cf_function_keyword,
    STATE(39), 1,
      sym_cf_if,
    STATE(56), 1,
      sym_cf_statement,
    STATE(57), 2,
      sym_cf_function,
      sym_cf_ifstatement,
  [1429] = 2,
    ACTIONS(203), 1,
      sym_text,
    ACTIONS(201), 5,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1440] = 2,
    ACTIONS(207), 1,
      sym_text,
    ACTIONS(205), 5,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1451] = 2,
    ACTIONS(211), 1,
      sym_text,
    ACTIONS(209), 5,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1462] = 5,
    ACTIONS(9), 1,
      sym_cf_if_keyword,
    ACTIONS(23), 1,
      sym_cf_function_keyword,
    STATE(38), 1,
      sym_cf_if,
    STATE(46), 1,
      sym_cf_statement,
    STATE(43), 2,
      sym_cf_function,
      sym_cf_ifstatement,
  [1479] = 2,
    ACTIONS(175), 1,
      sym_text,
    ACTIONS(173), 5,
      sym_cf_tag_start,
      sym_cf_tag_close,
      anon_sym_RBRACE,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1490] = 2,
    ACTIONS(199), 1,
      sym_text,
    ACTIONS(197), 4,
      ts_builtin_sym_end,
      sym_cf_tag_start,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1500] = 2,
    ACTIONS(179), 1,
      sym_text,
    ACTIONS(177), 4,
      ts_builtin_sym_end,
      sym_cf_tag_start,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1510] = 2,
    ACTIONS(195), 1,
      sym_text,
    ACTIONS(193), 4,
      ts_builtin_sym_end,
      sym_cf_tag_start,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1520] = 2,
    ACTIONS(207), 1,
      sym_text,
    ACTIONS(205), 4,
      ts_builtin_sym_end,
      sym_cf_tag_start,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1530] = 2,
    ACTIONS(175), 1,
      sym_text,
    ACTIONS(173), 4,
      ts_builtin_sym_end,
      sym_cf_tag_start,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1540] = 2,
    ACTIONS(203), 1,
      sym_text,
    ACTIONS(201), 4,
      ts_builtin_sym_end,
      sym_cf_tag_start,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1550] = 2,
    ACTIONS(191), 1,
      sym_text,
    ACTIONS(189), 4,
      ts_builtin_sym_end,
      sym_cf_tag_start,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1560] = 2,
    ACTIONS(187), 1,
      sym_text,
    ACTIONS(185), 4,
      ts_builtin_sym_end,
      sym_cf_tag_start,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1570] = 2,
    ACTIONS(183), 1,
      sym_text,
    ACTIONS(181), 4,
      ts_builtin_sym_end,
      sym_cf_tag_start,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1580] = 2,
    ACTIONS(211), 1,
      sym_text,
    ACTIONS(209), 4,
      ts_builtin_sym_end,
      sym_cf_tag_start,
      sym_cf_if_keyword,
      sym_cf_function_keyword,
  [1590] = 3,
    ACTIONS(223), 1,
      sym_cf_tag_end,
    ACTIONS(225), 1,
      sym_attribute_name,
    STATE(79), 2,
      sym_attribute,
      aux_sym_cf_function_repeat1,
  [1601] = 3,
    ACTIONS(225), 1,
      sym_attribute_name,
    ACTIONS(227), 1,
      sym_cf_tag_end,
    STATE(78), 2,
      sym_attribute,
      aux_sym_cf_function_repeat1,
  [1612] = 3,
    ACTIONS(225), 1,
      sym_attribute_name,
    ACTIONS(229), 1,
      sym_cf_tag_end,
    STATE(80), 2,
      sym_attribute,
      aux_sym_cf_function_repeat1,
  [1623] = 3,
    ACTIONS(225), 1,
      sym_attribute_name,
    ACTIONS(231), 1,
      sym_cf_tag_end,
    STATE(80), 2,
      sym_attribute,
      aux_sym_cf_function_repeat1,
  [1634] = 3,
    ACTIONS(233), 1,
      sym_cf_tag_end,
    ACTIONS(235), 1,
      sym_attribute_name,
    STATE(80), 2,
      sym_attribute,
      aux_sym_cf_function_repeat1,
  [1645] = 4,
    ACTIONS(238), 1,
      anon_sym_SQUOTE,
    ACTIONS(240), 1,
      anon_sym_DQUOTE,
    ACTIONS(242), 1,
      sym_attribute_value,
    STATE(95), 1,
      sym_quoted_attribute_value,
  [1658] = 3,
    ACTIONS(225), 1,
      sym_attribute_name,
    ACTIONS(244), 1,
      sym_cf_tag_end,
    STATE(83), 2,
      sym_attribute,
      aux_sym_cf_function_repeat1,
  [1669] = 3,
    ACTIONS(225), 1,
      sym_attribute_name,
    ACTIONS(246), 1,
      sym_cf_tag_end,
    STATE(80), 2,
      sym_attribute,
      aux_sym_cf_function_repeat1,
  [1680] = 3,
    ACTIONS(157), 1,
      sym_cf_tag_close,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      sym_cf_if_end,
  [1690] = 3,
    ACTIONS(165), 1,
      sym_cf_tag_close,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_cf_if_end,
  [1700] = 3,
    ACTIONS(157), 1,
      sym_cf_tag_close,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym_cf_if_end,
  [1710] = 2,
    ACTIONS(250), 1,
      anon_sym_EQ,
    ACTIONS(248), 2,
      sym_cf_tag_end,
      sym_attribute_name,
  [1718] = 3,
    ACTIONS(165), 1,
      sym_cf_tag_close,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      sym_cf_if_end,
  [1728] = 3,
    ACTIONS(169), 1,
      sym_cf_tag_close,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      sym_cf_if_end,
  [1738] = 3,
    ACTIONS(169), 1,
      sym_cf_tag_close,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      sym_cf_if_end,
  [1748] = 2,
    ACTIONS(252), 1,
      sym_cf_elseif_keyword,
    ACTIONS(254), 1,
      sym_cf_else_keyword,
  [1755] = 1,
    ACTIONS(256), 2,
      sym_cf_tag_end,
      sym_attribute_name,
  [1760] = 2,
    ACTIONS(258), 1,
      anon_sym_SQUOTE,
    ACTIONS(260), 1,
      aux_sym_quoted_attribute_value_token1,
  [1767] = 2,
    ACTIONS(258), 1,
      anon_sym_DQUOTE,
    ACTIONS(262), 1,
      aux_sym_quoted_attribute_value_token2,
  [1774] = 1,
    ACTIONS(264), 2,
      sym_cf_tag_end,
      sym_attribute_name,
  [1779] = 1,
    ACTIONS(266), 2,
      sym_cf_tag_end,
      sym_attribute_name,
  [1784] = 1,
    ACTIONS(268), 1,
      sym_cf_function_keyword,
  [1788] = 1,
    ACTIONS(270), 1,
      anon_sym_GT,
  [1792] = 1,
    ACTIONS(272), 1,
      sym_cf_tag_end,
  [1796] = 1,
    ACTIONS(274), 1,
      sym_cf_tag_end,
  [1800] = 1,
    ACTIONS(276), 1,
      sym_cf_tag_end,
  [1804] = 1,
    ACTIONS(278), 1,
      sym_cf_condition,
  [1808] = 1,
    ACTIONS(280), 1,
      sym_cf_if_keyword,
  [1812] = 1,
    ACTIONS(282), 1,
      anon_sym_GT,
  [1816] = 1,
    ACTIONS(284), 1,
      sym_cf_tag_end,
  [1820] = 1,
    ACTIONS(286), 1,
      sym_cf_tag_end,
  [1824] = 1,
    ACTIONS(288), 1,
      sym_cf_tag_end,
  [1828] = 1,
    ACTIONS(290), 1,
      sym_cf_if_keyword,
  [1832] = 1,
    ACTIONS(292), 1,
      sym_cf_function_keyword,
  [1836] = 1,
    ACTIONS(294), 1,
      sym_cf_function_keyword,
  [1840] = 1,
    ACTIONS(296), 1,
      sym_cf_function_keyword,
  [1844] = 1,
    ACTIONS(298), 1,
      sym_cf_if_keyword,
  [1848] = 1,
    ACTIONS(300), 1,
      sym_cf_function_keyword,
  [1852] = 1,
    ACTIONS(302), 1,
      sym_cf_function_keyword,
  [1856] = 1,
    ACTIONS(304), 1,
      sym_cf_function_keyword,
  [1860] = 1,
    ACTIONS(252), 1,
      sym_cf_elseif_keyword,
  [1864] = 1,
    ACTIONS(306), 1,
      sym_cf_function_keyword,
  [1868] = 1,
    ACTIONS(308), 1,
      sym_cf_condition,
  [1872] = 1,
    ACTIONS(310), 1,
      anon_sym_GT,
  [1876] = 1,
    ACTIONS(312), 1,
      sym_cf_tag_end,
  [1880] = 1,
    ACTIONS(314), 1,
      ts_builtin_sym_end,
  [1884] = 1,
    ACTIONS(316), 1,
      sym_cf_tag_end,
  [1888] = 1,
    ACTIONS(318), 1,
      sym_cf_condition,
  [1892] = 1,
    ACTIONS(320), 1,
      sym_cf_function_keyword,
  [1896] = 1,
    ACTIONS(322), 1,
      anon_sym_DQUOTE,
  [1900] = 1,
    ACTIONS(322), 1,
      anon_sym_SQUOTE,
  [1904] = 1,
    ACTIONS(324), 1,
      sym_cf_tag_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 139,
  [SMALL_STATE(7)] = 172,
  [SMALL_STATE(8)] = 203,
  [SMALL_STATE(9)] = 234,
  [SMALL_STATE(10)] = 267,
  [SMALL_STATE(11)] = 300,
  [SMALL_STATE(12)] = 333,
  [SMALL_STATE(13)] = 364,
  [SMALL_STATE(14)] = 395,
  [SMALL_STATE(15)] = 427,
  [SMALL_STATE(16)] = 459,
  [SMALL_STATE(17)] = 488,
  [SMALL_STATE(18)] = 517,
  [SMALL_STATE(19)] = 546,
  [SMALL_STATE(20)] = 575,
  [SMALL_STATE(21)] = 604,
  [SMALL_STATE(22)] = 633,
  [SMALL_STATE(23)] = 661,
  [SMALL_STATE(24)] = 689,
  [SMALL_STATE(25)] = 717,
  [SMALL_STATE(26)] = 745,
  [SMALL_STATE(27)] = 773,
  [SMALL_STATE(28)] = 801,
  [SMALL_STATE(29)] = 829,
  [SMALL_STATE(30)] = 857,
  [SMALL_STATE(31)] = 885,
  [SMALL_STATE(32)] = 913,
  [SMALL_STATE(33)] = 941,
  [SMALL_STATE(34)] = 969,
  [SMALL_STATE(35)] = 997,
  [SMALL_STATE(36)] = 1025,
  [SMALL_STATE(37)] = 1051,
  [SMALL_STATE(38)] = 1077,
  [SMALL_STATE(39)] = 1103,
  [SMALL_STATE(40)] = 1129,
  [SMALL_STATE(41)] = 1155,
  [SMALL_STATE(42)] = 1181,
  [SMALL_STATE(43)] = 1194,
  [SMALL_STATE(44)] = 1207,
  [SMALL_STATE(45)] = 1220,
  [SMALL_STATE(46)] = 1233,
  [SMALL_STATE(47)] = 1246,
  [SMALL_STATE(48)] = 1259,
  [SMALL_STATE(49)] = 1272,
  [SMALL_STATE(50)] = 1285,
  [SMALL_STATE(51)] = 1298,
  [SMALL_STATE(52)] = 1311,
  [SMALL_STATE(53)] = 1329,
  [SMALL_STATE(54)] = 1340,
  [SMALL_STATE(55)] = 1357,
  [SMALL_STATE(56)] = 1368,
  [SMALL_STATE(57)] = 1379,
  [SMALL_STATE(58)] = 1390,
  [SMALL_STATE(59)] = 1401,
  [SMALL_STATE(60)] = 1412,
  [SMALL_STATE(61)] = 1429,
  [SMALL_STATE(62)] = 1440,
  [SMALL_STATE(63)] = 1451,
  [SMALL_STATE(64)] = 1462,
  [SMALL_STATE(65)] = 1479,
  [SMALL_STATE(66)] = 1490,
  [SMALL_STATE(67)] = 1500,
  [SMALL_STATE(68)] = 1510,
  [SMALL_STATE(69)] = 1520,
  [SMALL_STATE(70)] = 1530,
  [SMALL_STATE(71)] = 1540,
  [SMALL_STATE(72)] = 1550,
  [SMALL_STATE(73)] = 1560,
  [SMALL_STATE(74)] = 1570,
  [SMALL_STATE(75)] = 1580,
  [SMALL_STATE(76)] = 1590,
  [SMALL_STATE(77)] = 1601,
  [SMALL_STATE(78)] = 1612,
  [SMALL_STATE(79)] = 1623,
  [SMALL_STATE(80)] = 1634,
  [SMALL_STATE(81)] = 1645,
  [SMALL_STATE(82)] = 1658,
  [SMALL_STATE(83)] = 1669,
  [SMALL_STATE(84)] = 1680,
  [SMALL_STATE(85)] = 1690,
  [SMALL_STATE(86)] = 1700,
  [SMALL_STATE(87)] = 1710,
  [SMALL_STATE(88)] = 1718,
  [SMALL_STATE(89)] = 1728,
  [SMALL_STATE(90)] = 1738,
  [SMALL_STATE(91)] = 1748,
  [SMALL_STATE(92)] = 1755,
  [SMALL_STATE(93)] = 1760,
  [SMALL_STATE(94)] = 1767,
  [SMALL_STATE(95)] = 1774,
  [SMALL_STATE(96)] = 1779,
  [SMALL_STATE(97)] = 1784,
  [SMALL_STATE(98)] = 1788,
  [SMALL_STATE(99)] = 1792,
  [SMALL_STATE(100)] = 1796,
  [SMALL_STATE(101)] = 1800,
  [SMALL_STATE(102)] = 1804,
  [SMALL_STATE(103)] = 1808,
  [SMALL_STATE(104)] = 1812,
  [SMALL_STATE(105)] = 1816,
  [SMALL_STATE(106)] = 1820,
  [SMALL_STATE(107)] = 1824,
  [SMALL_STATE(108)] = 1828,
  [SMALL_STATE(109)] = 1832,
  [SMALL_STATE(110)] = 1836,
  [SMALL_STATE(111)] = 1840,
  [SMALL_STATE(112)] = 1844,
  [SMALL_STATE(113)] = 1848,
  [SMALL_STATE(114)] = 1852,
  [SMALL_STATE(115)] = 1856,
  [SMALL_STATE(116)] = 1860,
  [SMALL_STATE(117)] = 1864,
  [SMALL_STATE(118)] = 1868,
  [SMALL_STATE(119)] = 1872,
  [SMALL_STATE(120)] = 1876,
  [SMALL_STATE(121)] = 1880,
  [SMALL_STATE(122)] = 1884,
  [SMALL_STATE(123)] = 1888,
  [SMALL_STATE(124)] = 1892,
  [SMALL_STATE(125)] = 1896,
  [SMALL_STATE(126)] = 1900,
  [SMALL_STATE(127)] = 1904,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_elseif, 3),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_elseif, 3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_elseif, 2),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_elseif, 2),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_if, 2),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_if, 2),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_elseif, 4),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_elseif, 4),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_if, 3),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_if, 3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_elseif, 5),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_elseif, 5),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_if, 4),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_if, 4),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(64),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(9),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(123),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(77),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_else, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_else, 1),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_else, 3),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(60),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(19),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(82),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_else, 4),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(54),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(24),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(76),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_function, 6),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_function, 6),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_statement, 1),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_statement, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_ifstatement, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_ifstatement, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_if_end, 1),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_if_end, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node, 2),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__node, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_function, 7),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_function, 7),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_ifstatement, 3),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_ifstatement, 3),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_if_end, 3),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_if_end, 3),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_ifstatement, 4),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_ifstatement, 4),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cf_function, 5),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cf_function, 5),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cf_ifstatement_repeat1, 2), SHIFT_REPEAT(116),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cf_ifstatement_repeat1, 2),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cf_ifstatement_repeat1, 2), SHIFT_REPEAT(102),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cf_ifstatement_repeat1, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cf_function_repeat1, 2),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cf_function_repeat1, 2), SHIFT_REPEAT(87),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [314] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cfml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
