name: Fuzz Parser

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "cfml/src/scanner.c"
      - "cfhtml/src/scanner.c"
      - "cfscript/src/scanner.c"
      - "cfquery/src/scanner.c"
      - "common/scanner.h"
      - "common/tag.h"
  push:
    branches:
      - "master"
    paths:
      - "cfml/src/scanner.c"
      - "cfhtml/src/scanner.c"
      - "cfscript/src/scanner.c"
      - "cfquery/src/scanner.c"
      - "common/scanner.h"
      - "common/tag.h"
  workflow_dispatch:

jobs:
  fuzz:
    name: Fuzz ${{ matrix.language }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [cfml, cfhtml, cfscript, cfquery]
    steps:
      - uses: actions/checkout@v3
      - uses: vigoux/tree-sitter-fuzz-action@v1
        with:
          language: ${{ matrix.language }}
          external-scanner: ${{ matrix.language }}/src/scanner.c
          time: 60
